### ISSUE TITLE
SQL repository raises error on async task

### ISSUE THREAD

**Issue by everthought** [Miksus/rocketry#171]
I was trying to set up a SQL repo for logging task status.
But after setting it up as described in the documentation, the task execution failed. -> https://rocketry.readthedocs.io/en/stable/cookbook/robust_applications.html#log-to-database
I think there must be a bug with the model or something.

If i used the MemoryRepo it worked as expected.
After some research i found the doku with setup.
https://rocketry.readthedocs.io/en/stable/cookbook/settings.html

Here the SQL repo worked as expekted.

The Code
repo = repo = SQLRepo(model=RunRecord, table="log", engine=db_engine, id_field="id")

app_scheduler = Rocketry(
    # logger_repo=MemoryRepo(),
    # logger_repo=repo,
    execution="async",
    config = {
    "task_execution": "async",
    }
    )

The exeption i encounterd.
2022-12-11 13:21:18	
rocketry.exc.TaskLoggingError: Logging for task 'check_starting_condition' failed.
2022-12-11 13:21:18	
    raise TaskLoggingError(f"Logging for task '{self.name}' failed.") from exc
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 1192, in _set_status
2022-12-11 13:21:18	
    self._set_status("fail", task_run)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 1080, in log_failure
2022-12-11 13:21:18	
    self.log_failure(task_run)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 527, in start_async
2022-12-11 13:21:18	
    await task.start_async(log_queue=self._log_queue)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/schedule.py", line 211, in run_task
2022-12-11 13:21:18	
    await self.run_task(task)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/schedule.py", line 182, in run_cycle
2022-12-11 13:21:18	
    await self.run_cycle()
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/schedule.py", line 128, in serve
2022-12-11 13:21:18	
Traceback (most recent call last):
2022-12-11 13:21:18	
The above exception was the direct cause of the following exception:
2022-12-11 13:21:18	
  field required (type=value_error.missing)
2022-12-11 13:21:18	
message
2022-12-11 13:21:18	
pydantic.error_wrappers.ValidationError: 1 validation error for RunRecord
2022-12-11 13:21:18	
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
2022-12-11 13:21:18	
    return self.model(**obj)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/base.py", line 338, in to_item
2022-12-11 13:21:18	
    item = self.to_item(item)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/base.py", line 192, in add
2022-12-11 13:21:18	
    self.repo.add(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/logging/handler.py", line 41, in write
2022-12-11 13:21:18	
    self.write(vars(record))
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/logging/handler.py", line 37, in emit
2022-12-11 13:21:18	
    self.emit(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
2022-12-11 13:21:18	
    hdlr.handle(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
2022-12-11 13:21:18	
    self.callHandlers(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
2022-12-11 13:21:18	
    self.handle(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
2022-12-11 13:21:18	
    self._log(level, msg, args, **kwargs)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1512, in log
2022-12-11 13:21:18	
    self.logger.log(level, msg, *args, **kwargs)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1844, in log
2022-12-11 13:21:18	
    self.log(ERROR, msg, *args, exc_info=exc_info, **kwargs)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1829, in exception
2022-12-11 13:21:18	
    log_method(
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 1181, in _set_status
2022-12-11 13:21:18	
Traceback (most recent call last):
2022-12-11 13:21:18	
During handling of the above exception, another exception occurred:
2022-12-11 13:21:18	
rocketry.exc.TaskLoggingError: Logging for task 'check_starting_condition' failed.
2022-12-11 13:21:18	
    raise TaskLoggingError(f"Logging for task '{self.name}' failed.") from exc
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 1192, in _set_status
2022-12-11 13:21:18	
    self._set_status("run", task_run)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 1076, in log_running
2022-12-11 13:21:18	
    self.log_running(task_run)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 500, in start_async
2022-12-11 13:21:18	
Traceback (most recent call last):
2022-12-11 13:21:18	
The above exception was the direct cause of the following exception:
2022-12-11 13:21:18	
  field required (type=value_error.missing)
2022-12-11 13:21:18	
message
2022-12-11 13:21:18	
pydantic.error_wrappers.ValidationError: 1 validation error for RunRecord
2022-12-11 13:21:18	
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
2022-12-11 13:21:18	
    return self.model(**obj)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/base.py", line 338, in to_item
2022-12-11 13:21:18	
    item = self.to_item(item)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/base.py", line 192, in add
2022-12-11 13:21:18	
    self.repo.add(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/logging/handler.py", line 41, in write
2022-12-11 13:21:18	
    self.write(vars(record))
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/redbird/logging/handler.py", line 37, in emit
2022-12-11 13:21:18	
    self.emit(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
2022-12-11 13:21:18	
    hdlr.handle(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
2022-12-11 13:21:18	
    self.callHandlers(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
2022-12-11 13:21:18	
    self.handle(record)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
2022-12-11 13:21:18	
    self._log(level, msg, args, **kwargs)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1512, in log
2022-12-11 13:21:18	
    self.logger.log(level, msg, *args, **kwargs)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1844, in log
2022-12-11 13:21:18	
    self.log(INFO, msg, *args, **kwargs)
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1806, in info
2022-12-11 13:21:18	
    log_method(
2022-12-11 13:21:18	
  File "/usr/local/lib/python3.9/site-packages/rocketry/core/task.py", line 1181, in _set_status
2022-12-11 13:21:18	
Traceback (most recent call last):
2022-12-11 13:21:18	
CRITICAL:rocketry.scheduler:Fatal error encountered. Shutting down...

**Comment by everthought** [comment]
After a lot of tinkering i found the issue.
The Documentation is misleading on this point.

I found out that there ist the open issue with the missing method app.session.set_repo().

For use with suggested Table 
```python 
engine.execute("""CREATE TABLE log (
    id INTEGER PRIMARY KEY,
    created FLOAT,
    task_name TEXT,
    run_id TEXT,
    action TEXT
)""")
```
The Model MinimalRunRecord shoud be used.

For setting up the Scheduler with the SQL Repo i used the following example.
```python 

app_scheduler = Rocketry(
    execution="async",
    # logger_repo=MemoryRepo(),
    logger_repo=SQLRepo(engine=db_engine, table="scheduler_log", model=MinimalRunRecord, id_field="id"),
    config = {
    "task_execution": "async",
    'silence_task_prerun': True,
    'silence_task_logging': True,
    'silence_cond_check': True,
    "force_status_from_logs": True
    }
    )
```

**Comment by Miksus** [comment]
Could you link the part of the docs you are looking at? I'm actually just finalizing quite a major update on the docs (rewrote the tutorials, added new parts to cookbook and handbook) and I could check that. 

I'm leaning on this could be the most standard way of setting the repo:

```python
@app.setup()
def set_repo(logger=TaskLogger()):
    repo = SQLRepo(engine=create_engine("sqlite:///app.db"), table="tasks", model=MinimalRecord, id_field="created")
    logger.set_repo(repo)
```

You can also use the ``logger_repo`` just fine if you prefer that but this has the benefit of that you could set the configs programmatically like:

```python
@app.setup()
def set_config(config=Config(), env=EnvArg("ENV", default="dev")):
    if env == "prod":
        config.silence_task_prerun = True
        config.silence_task_logging = True
        config.silence_cond_check = True
    else:
        config.silence_task_prerun = False
        config.silence_task_logging = False
        config.silence_cond_check = False
```

I probably will add the ``set_repo`` as a convenient method to session as well but at the moment it is found from the task logger which can be acquired by the argument system (see the previous example).

The ``SQLRepo`` is quite problematic in terms of implementation as it relies on reflecting SQLAlchemy's ORM models which are sometimes quite a mess. I'm planning of using the SQL expressions at some point so that at least the primary key requirement wouldn't be there.
